// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bang.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bang_EscapeMethod int32

const (
	Bang_QUERY_ESCAPE Bang_EscapeMethod = 0
	Bang_PASS_THROUGH Bang_EscapeMethod = 1
	Bang_PATH_ESCAPE  Bang_EscapeMethod = 2
)

var Bang_EscapeMethod_name = map[int32]string{
	0: "QUERY_ESCAPE",
	1: "PASS_THROUGH",
	2: "PATH_ESCAPE",
}

var Bang_EscapeMethod_value = map[string]int32{
	"QUERY_ESCAPE": 0,
	"PASS_THROUGH": 1,
	"PATH_ESCAPE":  2,
}

func (x Bang_EscapeMethod) String() string {
	return proto.EnumName(Bang_EscapeMethod_name, int32(x))
}

func (Bang_EscapeMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a267da1eca5e2d1b, []int{0, 0}
}

type Bang struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Format               string            `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Description          string            `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Unescaped            bool              `protobuf:"varint,4,opt,name=unescaped,proto3" json:"unescaped,omitempty"`
	EscapeMethod         Bang_EscapeMethod `protobuf:"varint,5,opt,name=escape_method,json=escapeMethod,proto3,enum=main.Bang_EscapeMethod" json:"escape_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Bang) Reset()         { *m = Bang{} }
func (m *Bang) String() string { return proto.CompactTextString(m) }
func (*Bang) ProtoMessage()    {}
func (*Bang) Descriptor() ([]byte, []int) {
	return fileDescriptor_a267da1eca5e2d1b, []int{0}
}

func (m *Bang) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bang.Unmarshal(m, b)
}
func (m *Bang) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bang.Marshal(b, m, deterministic)
}
func (m *Bang) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bang.Merge(m, src)
}
func (m *Bang) XXX_Size() int {
	return xxx_messageInfo_Bang.Size(m)
}
func (m *Bang) XXX_DiscardUnknown() {
	xxx_messageInfo_Bang.DiscardUnknown(m)
}

var xxx_messageInfo_Bang proto.InternalMessageInfo

func (m *Bang) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Bang) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Bang) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Bang) GetUnescaped() bool {
	if m != nil {
		return m.Unescaped
	}
	return false
}

func (m *Bang) GetEscapeMethod() Bang_EscapeMethod {
	if m != nil {
		return m.EscapeMethod
	}
	return Bang_QUERY_ESCAPE
}

func init() {
	proto.RegisterEnum("main.Bang_EscapeMethod", Bang_EscapeMethod_name, Bang_EscapeMethod_value)
	proto.RegisterType((*Bang)(nil), "main.Bang")
}

func init() { proto.RegisterFile("bang.proto", fileDescriptor_a267da1eca5e2d1b) }

var fileDescriptor_a267da1eca5e2d1b = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0x31, 0x15, 0xbd, 0x06, 0x88, 0x6e, 0x00, 0x0f, 0x0c, 0x56, 0xa7, 0x4c, 0x1e,
	0x60, 0x65, 0x09, 0x95, 0x45, 0x16, 0x44, 0x70, 0xda, 0x81, 0x29, 0x72, 0x1b, 0x13, 0x32, 0xd8,
	0x8e, 0x12, 0xf3, 0xd3, 0xd9, 0x51, 0x0c, 0x88, 0x6c, 0xef, 0x7d, 0xdf, 0x0d, 0x4f, 0x07, 0x70,
	0xd0, 0xae, 0x15, 0xfd, 0xe0, 0x83, 0x47, 0x6a, 0x75, 0xe7, 0x36, 0x5f, 0x04, 0xe8, 0xa3, 0x76,
	0x2d, 0x22, 0x50, 0xa7, 0xad, 0x61, 0x84, 0x93, 0x6c, 0xa5, 0x62, 0xc6, 0x6b, 0x58, 0xbe, 0xfb,
	0xc1, 0xea, 0xc0, 0x16, 0x91, 0xfe, 0x36, 0xe4, 0xb0, 0x6e, 0xcc, 0x78, 0x1c, 0xba, 0x3e, 0x74,
	0xde, 0xb1, 0xd3, 0x28, 0xe7, 0x08, 0x6f, 0x61, 0xf5, 0xe9, 0xcc, 0x78, 0xd4, 0xbd, 0x69, 0x18,
	0xe5, 0x24, 0x3b, 0x57, 0xff, 0x00, 0x1f, 0xe0, 0xe2, 0x27, 0xd6, 0xd6, 0x84, 0x0f, 0xdf, 0xb0,
	0x33, 0x4e, 0xb2, 0xcb, 0xbb, 0x1b, 0x31, 0x4d, 0x12, 0xd3, 0x1c, 0x21, 0xa3, 0x7f, 0x8e, 0x5a,
	0x25, 0x66, 0xd6, 0x36, 0x5b, 0x48, 0xe6, 0x16, 0x53, 0x48, 0x5e, 0xf7, 0x52, 0xbd, 0xd5, 0xb2,
	0xda, 0xe6, 0xa5, 0x4c, 0x4f, 0x26, 0x52, 0xe6, 0x55, 0x55, 0xef, 0x0a, 0xf5, 0xb2, 0x7f, 0x2a,
	0x52, 0x82, 0x57, 0xb0, 0x2e, 0xf3, 0x5d, 0xf1, 0x77, 0xb2, 0x38, 0x2c, 0xe3, 0x13, 0xee, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x36, 0xca, 0x3b, 0x12, 0x01, 0x00, 0x00,
}
