// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bang.proto

package bang

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// EscapeMethod is the type of escaping to be used when escaping non-URL
// safe characters, like spaces and quotes.
type Bang_EscapeMethod int32

const (
	// Escapes the input with url.QueryEscape: "cat pictures" => "cat+pictures"
	Bang_QUERY_ESCAPE Bang_EscapeMethod = 0
	// Does no escaping: "cat pictures" => "cat pictures"
	Bang_PASS_THROUGH Bang_EscapeMethod = 1
	// Escapes the input with url.PathEscape: "cat pictures" => "cat%20pictures"
	Bang_PATH_ESCAPE Bang_EscapeMethod = 2
)

var Bang_EscapeMethod_name = map[int32]string{
	0: "QUERY_ESCAPE",
	1: "PASS_THROUGH",
	2: "PATH_ESCAPE",
}

var Bang_EscapeMethod_value = map[string]int32{
	"QUERY_ESCAPE": 0,
	"PASS_THROUGH": 1,
	"PATH_ESCAPE":  2,
}

func (x Bang_EscapeMethod) String() string {
	return proto.EnumName(Bang_EscapeMethod_name, int32(x))
}

func (Bang_EscapeMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a267da1eca5e2d1b, []int{0, 0}
}

type Bang struct {
	// Name of the Bang, which is used as its ID.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Format of the Bang, where '{{{s}}}' will be substituted with the escaped
	// query string.
	Format string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	// Description is a summary of the Bang.
	Description          string            `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	EscapeMethod         Bang_EscapeMethod `protobuf:"varint,4,opt,name=escape_method,json=escapeMethod,proto3,enum=bang.Bang_EscapeMethod" json:"escape_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Bang) Reset()         { *m = Bang{} }
func (m *Bang) String() string { return proto.CompactTextString(m) }
func (*Bang) ProtoMessage()    {}
func (*Bang) Descriptor() ([]byte, []int) {
	return fileDescriptor_a267da1eca5e2d1b, []int{0}
}

func (m *Bang) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bang.Unmarshal(m, b)
}
func (m *Bang) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bang.Marshal(b, m, deterministic)
}
func (m *Bang) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bang.Merge(m, src)
}
func (m *Bang) XXX_Size() int {
	return xxx_messageInfo_Bang.Size(m)
}
func (m *Bang) XXX_DiscardUnknown() {
	xxx_messageInfo_Bang.DiscardUnknown(m)
}

var xxx_messageInfo_Bang proto.InternalMessageInfo

func (m *Bang) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Bang) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Bang) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Bang) GetEscapeMethod() Bang_EscapeMethod {
	if m != nil {
		return m.EscapeMethod
	}
	return Bang_QUERY_ESCAPE
}

func init() {
	proto.RegisterEnum("bang.Bang_EscapeMethod", Bang_EscapeMethod_name, Bang_EscapeMethod_value)
	proto.RegisterType((*Bang)(nil), "bang.Bang")
}

func init() { proto.RegisterFile("bang.proto", fileDescriptor_a267da1eca5e2d1b) }

var fileDescriptor_a267da1eca5e2d1b = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0xcc, 0x4b,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xae, 0x33, 0x72, 0xb1, 0x38,
	0x25, 0xe6, 0xa5, 0x0b, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x81, 0xd9, 0x42, 0x62, 0x5c, 0x6c, 0x69, 0xf9, 0x45, 0xb9, 0x89, 0x25, 0x12, 0x4c,
	0x60, 0x51, 0x28, 0x4f, 0x48, 0x81, 0x8b, 0x3b, 0x25, 0xb5, 0x38, 0xb9, 0x28, 0xb3, 0xa0, 0x24,
	0x33, 0x3f, 0x4f, 0x82, 0x19, 0x2c, 0x89, 0x2c, 0x24, 0x64, 0xc3, 0xc5, 0x9b, 0x5a, 0x9c, 0x9c,
	0x58, 0x90, 0x1a, 0x9f, 0x9b, 0x5a, 0x92, 0x91, 0x9f, 0x22, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x67,
	0x24, 0xae, 0x07, 0x76, 0x00, 0xc8, 0x42, 0x3d, 0x57, 0xb0, 0xbc, 0x2f, 0x58, 0x3a, 0x88, 0x27,
	0x15, 0x89, 0xa7, 0xe4, 0xcc, 0xc5, 0x83, 0x2c, 0x2b, 0x24, 0xc0, 0xc5, 0x13, 0x18, 0xea, 0x1a,
	0x14, 0x19, 0xef, 0x1a, 0xec, 0xec, 0x18, 0xe0, 0x2a, 0xc0, 0x00, 0x12, 0x09, 0x70, 0x0c, 0x0e,
	0x8e, 0x0f, 0xf1, 0x08, 0xf2, 0x0f, 0x75, 0xf7, 0x10, 0x60, 0x14, 0xe2, 0xe7, 0xe2, 0x0e, 0x70,
	0x0c, 0xf1, 0x80, 0x29, 0x61, 0x4a, 0x62, 0x03, 0x7b, 0xd3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x33, 0x1a, 0x0e, 0x41, 0xf4, 0x00, 0x00, 0x00,
}
