// Code generated by go-bindata.
// sources:
// bangs.json
// DO NOT EDIT!

package main

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _bangsJson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xbc\x92\x41\x4b\xc4\x30\x10\x85\xef\xfd\x15\x43\x40\x4f\x6b\x7b\x2f\x2c\x0b\x5e\xd4\x83\x28\xbb\x07\x8f\x92\xb4\x31\x1d\xb6\x6d\xe2\x24\xb5\x88\xec\x7f\x97\x26\x0a\xae\xee\x74\xf5\xb0\x5e\x4a\xdb\x0c\xef\x7b\xef\x65\xde\x32\x00\xa1\x50\x94\x30\xbd\x01\x88\x5a\xfb\x8a\xd0\x05\xb4\xbd\x28\x41\x5c\x62\x6f\xe0\xa6\x93\x46\x7b\xb1\x48\x13\x4f\x96\x3a\x19\xa6\xc3\x26\x04\xe7\xcb\xa2\x18\xc7\x31\x57\xd8\x9b\xbc\xb2\x5d\x81\x71\xb8\xf0\x5a\x52\xd5\xac\x9e\x97\x67\x5e\x64\x00\xbb\x45\x02\xf5\x26\x9d\xff\x13\xd0\xb0\x9c\x2b\x6b\x4d\xab\xe7\x11\x26\xce\x44\xc8\x61\xf5\x86\x97\xc7\x70\x3d\x28\x5e\xde\x60\x68\x06\x35\x23\xcd\x5f\x49\x72\xfe\xab\x8e\x7e\x06\x08\xaa\x5b\xa2\xaf\x9a\xf3\x6f\xb8\xd4\xc6\x49\xcb\xa2\xa3\x91\xd6\xfa\x45\x93\xff\x88\x06\x9b\xa8\x72\x18\xca\x31\xd5\x6b\xdc\x86\x55\x7c\x3e\x0e\xd4\xee\x59\xc0\xce\x58\xc7\xaf\x5e\xc2\xde\x39\x4d\x72\xfa\xe5\xe1\x56\x07\x79\x11\xac\x6d\xf9\xe4\x49\x32\x3a\xf8\x4a\x22\x16\xb2\xd6\x75\x8d\x61\xbe\x4a\x8a\x33\x7c\x95\xe9\x9c\x0f\x92\x18\xe0\x07\x45\x7f\xa3\xd1\x7e\x88\xe3\x4b\x78\xea\x1b\x1b\x59\x03\x0f\xb8\xc5\x7b\x5d\xa3\x9c\x09\x87\x5b\x74\xd3\x48\x6e\xc9\xc4\xaf\x62\xe3\x74\x85\xb2\x2d\x93\xd3\xcf\xb4\xd9\x2e\x7b\x0f\x00\x00\xff\xff\xf7\x74\xf7\xc0\x08\x05\x00\x00")

func bangsJsonBytes() ([]byte, error) {
	return bindataRead(
		_bangsJson,
		"bangs.json",
	)
}

func bangsJson() (*asset, error) {
	bytes, err := bangsJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bangs.json", size: 1288, mode: os.FileMode(420), modTime: time.Unix(1545270664, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"bangs.json": bangsJson,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"bangs.json": &bintree{bangsJson, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
